apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "selectorLabels" . | nindent 4 }}
    {{- include "labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "selectorLabels" . | nindent 8 }}
        {{- include "labels" . | nindent 8 }}
    spec:
      serviceAccountName: bestgres-operator
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "operatorImage" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- include "envVars" . | nindent 12 }}