---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bestgres-operator
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bestgres-operator
subjects:
  - kind: ServiceAccount
    name: bestgres-operator
    namespace: {{ .Release.Namespace }}
