---
apiVersion: bestgres.io/v1
kind: BGCluster
metadata:
  name: bgcluster
spec:
  instances: 2
  volumeSpec:
    persistentVolumeSize: "1Gi"
    storageClass: "hostpath"
  patroniLogLevel: "INFO"
  image:
    tag: spilo:16
