apiVersion: bestgres.io/v1
kind: BGCluster
metadata:
  name: test-bgcluster
spec:
  instances: 1
  persistentVolumeSize: "1Gi"
  storageClass: "hostpath"
  patroniLogLevel: "DEBUG"
  image:
    tag: spilo:16
