apiVersion: bestgres.io/v1
kind: BGCluster
metadata:
  name: example-bgcluster
spec:
  instances: 1
  persistentVolumeSize: "1Gi"
  storageClass: "hostpath"
  superuserPassword: "password"
  replicationPassword: "replicapassword"
  patroni:
    image: "patroni/patroni:3.3.1"
