---
apiVersion: bestgres.io/v1
kind: BGShardedCluster
metadata:
  name: bgshardedcluster
spec:
  shards: 2
  coordinator:
    instances: 1
    volumeSpec:
      persistentVolumeSize: 1Gi
      storageClass: hostpath
    image:
      tag: spilo:16-citus
  workers:
    instances: 1
    volumeSpec:
      persistentVolumeSize: 1Gi
      storageClass: hostpath
    image:
      tag: spilo:16-citus